# This file shows how to run multi-node training benchmarks using an MPIJob,
# specifying GPUs explicitly.
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: tensorflow-benchmarks-8
spec:
  replicas: 8
  template:
    spec:
      containers:
      - image: mpioperator/tensorflow-benchmarks:latest
        name: tensorflow-benchmarks
        resources:
          limits:
            nvidia.com/gpu: 1
