# This file shows how to run multi-node training benchmarks using an MPIJob,
# letting the operator decide on how best to allocate GPUs.
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: tensorflow-benchmarks-16
spec:
  gpus: 16
  template:
    spec:
      containers:
      - image: mpioperator/tensorflow-benchmarks:latest
        name: tensorflow-benchmarks
